name: RaplexMercado
version: 1.3-SNAPSHOT
author: metehus
main: raplexmarket.RaplexMarket
depend: ['Vault']
commands:
  market:
    description: Opens the shop menu.
    usage: /market
    aliases: ["mercado"]